name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Checkstyle
        run: |
          curl -LO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-9.2/checkstyle-9.2-all.jar
          java -jar checkstyle-9.2-all.jar -c /google_checks.xml src

      - name: Run Google Java Format
        run: |
          curl -LO https://github.com/google/google-java-format/releases/download/v1.9/google-java-format-1.9-all-deps.jar
          java -jar google-java-format-1.9-all-deps.jar -i $(find . -name '*.java')
