name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List files in the repository
        run: ls -R

      - name: Download Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-9.2/checkstyle-9.2-all.jar
          ls -l checkstyle-9.2-all.jar
          file checkstyle-9.2-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle-9.2-all.jar -c /google_checks.xml src/

      - name: Download Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/download/v1.9/google-java-format-1.9-all-deps.jar
          ls -l google-java-format-1.9-all-deps.jar
          file google-java-format-1.9-all-deps.jar

      - name: Run Google Java Format
        run: |
          java -jar google-java-format-1.9-all-deps.jar -i $(find src/ -name '*.java')
